### ISSUE TITLE
Clarification of license

### ISSUE THREAD

**Issue by eilwenfae** [egbertn/ispsession.io#2]
Hiya,

Some confusion over the license, main README says opensource, but doesn't say which license is being used; it looks like there's been changes to MIT in some of the code, but there's references to more commercial license:
* src/License 2016.txt
* docs/License Agreement.rtf
* setup/COM/License 2016.txt

I don't know if there's any other mentions. Could the README be explicit on which license applies as it's a bit confusing.

**Comment by egbertn** [comment]
H

> 
> 
> Hiya,
> 
> Some confusion over the license, main README says opensource, but doesn't say which license is being used; it looks like there's been changes to MIT in some of the code, but there's references to more commercial license:
> 
>     * src/License 2016.txt
> 
>     * docs/License Agreement.rtf
> 
>     * setup/COM/License 2016.txt
> 
> 
> I don't know if there's any other mentions. Could the README be explicit on which license applies as it's a bit confusing.

These files have been removed Now. Thanks.
